################################# Default configuration ###################
baseURL = "/"
title = "Meghna"
theme = "tcop"
# themesDir = "/tcop"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []




[params]
    logo = "images/logo.png?nf_resize=fit&w=100&h=200"
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "2 Jan, 2006"
    email                        = "support@attomus.com"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/London"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "hh:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = false
        googlePlus               = false
        pinterest                = false

[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Tempestas Copper"
        [languages.en.params]
            description  = "Tempestas Copper - sustainable mining claims in Arizona"   # Max 160 characters show in search results
            footerText   = "supported by [attomus](https://attomus.com)"   # Text to override default footer text  (markdown allowed)


################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
pre = "#"
url = "about"
weight = 1

#[[Languages.en.menu.main]]
#name = "services"
#pre = "#"
#url = "services"
#weight = 2

[[Languages.en.menu.main]]
name = "Imagery"
pre = "#"
url = "imagery"
weight = 3

[[Languages.en.menu.main]]
name = "Team"
pre = "#"
url = "team"
weight = 4

#[[Languages.en.menu.main]]
#name = "pricing"
#pre = "#"
#url = "pricing"
#weight = 5

[[Languages.en.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7




############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
